package:
  name: pylearn2
  version: 2

source:
  git_url: https://github.com/lisa-lab/pylearn2.git
  patches: 
    - patch.diff

requirements:
  build:
    - python
    - cython 0.22
    - setuptools
    - matplotlib
    #- theano >=0.7.0
    - pyyaml
    - pil

  run:
    - python
    - cython 0.22
    - matplotlib
    #- theano >=0.7.0
    - pyyaml
    - pil

#test:
  # Python imports
  #imports:

about:
  home: http://deeplearning.net/software/pylearn2/#
  license: BSD License